server:
  port: 8443
  ssl:
    key-store: file:///opt/misc/tacos/mykeys.jks
    key-store-password: letmein
    key-password: letmein
spring:
  profiles:
    active:
      - dev
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
taco:
  orders:
    pageSize: 10

logging:
  level:
    root: ERROR
    emg:
      tacos: ERROR

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    emg:
      taco: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql:/ /localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    root: WARN
    emg:
      taco: WARN
