server:
  port: 8443
spring:
  profiles:
    active:
      - dev
  data:
    rest:
      base-path: /data-api
taco:
  orders:
    pageSize: 10

---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
  devtools:
    livereload:
      enabled: true
logging:
  level:
    root: INFO
    emg:
      taco: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql:/ /localhost/tacocloud
    username: tacouser
    password: tacopassword
server:
  ssl:
    key-store: file:///opt/misc/tacos/mykeys.jks
    key-store-password: letmein
    key-password: letmein
logging:
  level:
    root: WARN
    emg:
      taco: WARN
